dir: '{{.InterfaceDir}}'
structname: Mock{{.InterfaceName}}
template: testify
packages:
  github.com/anonpragmatic/gowaves/pkg/networking:
    interfaces:
      Handler: {}
      Header: {}
      Protocol: {}
  github.com/anonpragmatic/gowaves/pkg/blockchaininfo:
    interfaces:
      UpdatesPublisherInterface: {}
